name: Inflammation CI

# Specify which Github action will trigger this CI build
on: push

jobs:

  build:

    # Specify OS to run tests on
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Test wit PyTest
      run: |
        python -m pytest --cov=inflammation.models tests/test_models.py